version: '3.8'

services:
  app:
    image: 'url-shortener:latest'
    build:
      context: .
    container_name: url-shortener-app
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "80:8080"
      - "5005:5005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/url-shortener
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.4-alpine'
    container_name: postgresql-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=url-shortener

volumes:
  postgres-data: